version: "3.6"
services:
  mysql:
    image: mysql:8
    container_name: cndb
    environment:
      MYSQL_DATABASE: cn
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - cn_network

  splash:
    build:
      context: ./scrape-it
      dockerfile: Dockerfile
    container_name: splash
    restart: unless-stopped
    ports:
      - "127.0.0.1:8050:8050"
    networks:
      - cn_network
    deploy:
      resources:
        limits:
          memory: 200M
  cnapi:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: cnapi
    restart: unless-stopped
    ports:
      - "127.0.0.1:3500:8080"
    depends_on:
      splash:
        condition: service_started
      mysql:
        condition: service_healthy
    networks:
      - cn_network

networks:
  cn_network:
    name: cn_network
    driver: bridge
