FROM golang:1.22-rc-alpine3.18

WORKDIR /go/src/app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /go/src/app/build/cnapi main.go

EXPOSE 8080

CMD ["/go/src/app/build/cnapi"]
