FROM golang:1.22-rc-alpine3.18 AS builder

WORKDIR /go/src/app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /go/src/app/build/cnapi main.go

FROM alpine:3.18 as runner

COPY --from=builder /go/src/app/build/cnapi /cnapi

EXPOSE 8080

CMD ["/cnapi"]
