name = "Hiru News"

[[languages]]
language = "si"
strategy = "html"
page_url = "https://www.hirunews.lk"
link_selectors = ["a.card-featured", "a.card-v1"]
url_prefix = "https://hirunews.lk/"
max_items = 5

[[languages]]
language = "en"
strategy = "html"
page_url = "https://www.hirunews.lk/en/"
link_selectors = ["a.card-featured", "a.card-v1"]
url_prefix = "https://hirunews.lk/"
max_items = 5

[[languages]]
language = "ta"
strategy = "html"
page_url = "https://www.hirunews.lk/tm/"
link_selectors = ["a.card-featured", "a.card-v1"]
url_prefix = "https://hirunews.lk/"
max_items = 5
