import { Source } from "./types/main";

export const sources: Source[] = [
	{
		name: "BBC Sinhala",
		language: "si",
		url: "https://www.bbc.com/sinhala/topics/cg7267dz901t",
		provider: "bbc.provider.ts",
		enabled: true,
	},
	{
		name: "Neth News",
		language: "si",
		url: "http://nethnews.lk/category/feed/5",
		provider: "rss.provider.ts",
		enabled: true,
	},
	{
		name: "News.lk",
		language: "si",
		url: "https://sinhala.news.lk/news",
		provider: "newslk.provider.ts",
		enabled: true,
	},
	{
		name: "Lanka Puvath",
		language: "si",
		url: "http://sinhala.lankapuvath.lk/category/local/",
		provider: "lankapuvath.provider.ts",
		enabled: true,
	},
	{
		name: "Hiru News",
		language: "si",
		url: "https://www.hirunews.lk/local-news.php?pageID=1",
		provider: "hirunews.provider.ts",
		enabled: false,
	},
	{
		name: "Srilanka Mirror",
		language: "si",
		url: "https://www.sinhala.srilankamirror.com/news?format=feed&type=rss",
		provider: "rss.provider.ts",
		enabled: true,
	},
	{
		name: "Gagana",
		language: "si",
		url: "https://gagana.lk/news/srilanka",
		provider: "gagana.provider.ts",
		enabled: true,
	},
	{
		name: "Mawrata",
		language: "si",
		url: "https://www.mawratanews.lk/feed",
		provider: "rss.provider.ts",
		enabled: true,
	},
	{
		name: "Divaina",
		language: "si",
		url: "https://divaina.lk/feed",
		provider: "rss.provider.ts",
		enabled: true,
	},
	{
		name: "Lankadeepa",
		language: "si",
		url: "https://www.lankadeepa.lk/rss/latest_news/1",
		provider: "rss.provider.ts",
		enabled: true,
	},
	{
		name: "Aruna",
		language: "si",
		url: "http://www.aruna.lk/feed",
		provider: "rss.provider.ts",
		enabled: true,
	},
	// english
	{
		name: "Daily News",
		language: "en",
		url: "https://www.dailynews.lk/taxonomy/term/799/%2A/feed",
		provider: "rss.provider.ts",
		enabled: true,
	},
	{
		name: "Hiru News",
		language: "en",
		url: "https://www.hirunews.lk/english/local-news.php",
		provider: "hirunews.provider.ts",
		enabled: false,
	},
	{
		name: "News.lk",
		language: "en",
		url: "https://news.lk/news",
		provider: "newslk.provider.ts",
		enabled: true,
	},
	{
		name: "Srilanka Mirror",
		language: "en",
		url: "https://www.srilankamirror.com/news?format=feed&type=rss",
		provider: "rss.provider.ts",
		enabled: true,
	},
	{
		name: "BBC",
		language: "en",
		url: "https://www.bbc.com/news/topics/cywd23g0gxgt/sri-lanka",
		provider: "bbc.provider.ts",
		enabled: true,
	},
	{
		name: "Sunday Observer",
		language: "en",
		url: "https://www.sundayobserver.lk/news",
		provider: "sundayobserver.provider.ts",
		enabled: true,
	},
	{
		name: "Colombo Page",
		language: "en",
		url: "http://colombopage.com",
		provider: "colombopage.provider.ts",
		enabled: true,
	},
	{
		name: "The Morning",
		language: "en",
		url: "https://www.themorning.lk/category/news/feed",
		provider: "rss.provider.ts",
		enabled: true,
	},
	//tamil
	{
		name: "Hiru News",
		language: "ta",
		url: "https://www.hirunews.lk/tamil/local-news.php",
		provider: "hirunews.provider.ts",
		enabled: false,
	},
	{
		name: "News.lk",
		language: "ta",
		url: "https://tamil.news.lk/news",
		provider: "newslk.provider.ts",
		enabled: true,
	},
	{
		name: "BBC",
		language: "ta",
		url: "https://www.bbc.com/tamil/topics/cz74k7p3qw7t",
		provider: "bbc.provider.ts",
		enabled: true,
	},
];
