name: Deploy
on:
  push:
    branches: ['go-rewrite']
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: deploy containers
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: /home/${{ secrets.SSH_USER }}/CeylonNewsBackendGo/CeylonNewsBackend/deploy.sh
